import {Badge} from './badge';
import {Pet} from './pet';
import {Rating} from './rating';
import {SpaceImage} from './space-image';
import {Listing} from './listing';
import {Service} from './service';
import {Space} from './space';
import {PetBreed} from './pet-breed';
import {Specialskills} from './specialskills';
import { BackgroundCheck } from './backgroundBadge';
import { RighttoWork } from './righttowork';
import { Animalcare } from './animalcare';
import { Progress } from './progress';
import { Notification } from './notification';
import {paypal} from './paypal';
import { stripe } from './stripe';
import { ndisprofile } from './ndis';

export class User {
    id: number;
    state: number = null;
    verify_phoneflag: string = 'N';
    experiencePets: number = null;
    longitude: string = null;
    latitude: string = null;
    experienceYears: string = null;
    qualifications: string = null;
    street_address: string = null;
    suburb: string = null;
    address: string = null;
    zipcode: string = null;
    first_name: string = '';
    about_pet: string = null;
    hasQualifications: number;
    timezone: string = 'Australia/Brisbane';
    last_name: string = null;
    imagename: string = null;
    gender: string = null;
    good_minder: string = null;
    spaceImages: [SpaceImage] = [null];
    listing: Listing;
    primaryServices: [Service] = [null];
    primaryServicesNew: [Service] = [null];
    secondaryServices: [Service] = [null];
    services: [Service] = [null];
    rating: Rating;
    pets: [Pet] = [null];
    petList: [Pet] = [null];
    badges: [Badge] = [null];
    space: Space = null;
    dob: string;
    training_flag: number = 0;
    petbreeds: [PetBreed] = [null];
    specialskills: [Specialskills] = [null];
    paypal:[paypal] = null;
    created_on: string = null;
    last_login: string = null;
    active: number = 0;
    verified: number = 0;
    phone: string = null;
    mobile: string = null;
    email: string;
    stripedConnectEnabled: string;
    stripeCardId: string = '';
    stripeCustomerId: string = '';
    user_type: any = null;
    paypal_email: string = '';
    sendMeSMS: number = 0;
    sendMePush: number = 0;
    sendMeEmail: number = 0;
    document_image: number = 0;
    facebook_id: number = 0;
    share_url: string = '';
    share_coupon:string = "";
    reference_flag: boolean = false;
    listingStatus: number = 1;
    stripeConnectEnabled: number;
    paypalSandboxId: string;  
    paypalMode: string;
    paypalProductionId: string;
    email_flag:number;
    lastCalendarUpdate:any;
    backgroundCheckDocument:any;
    BackgroundCheck:  [BackgroundCheck] = [null];
    righttowork: [RighttoWork] = [null]
    animalcare:[Animalcare] = [null]
    stripe:[stripe] = [null]
    isBackgroundChecked : boolean = false;
    isRightToWorkChecked: boolean = false;
    isAnimalCareChecked: boolean = false;
    stripe_card:any
    account:any
    stripe_connect_update: any = null;
    auto_recharge: number = 0;
    progress: [Progress] = [null];
    progressShow: number = 0;
    notifications: [Notification] = [null];
    multipleBooked: boolean = false;
    app_review:any = 0;
    role:any = "";
    accessToken = "";
    ndisprofile: [ndisprofile] = null;
}
